version: "2"
services:

  postgres:
    image: postgres:9.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=TCrGaanoC2s7gT
    volumes:
      - /var/lib/postgresql/data

  zookeeper:
    container_name: zookeeper
    image: znly/zookeeper:3.4.8
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper
    ports:
      - "2181:2181"

  overlord:
#    image: znly/druid:0.9.1.1
    build: .
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - overlord

  coordinator:
#    image: znly/druid:0.9.1.1
    build: .
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - coordinator
    ports:
      - "8081:8081"


  middlemanager:
#    image: znly/druid:0.9.1.1
    build: .
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - middleManager

  historical:
#    image: znly/druid:0.9.1.1
    build: .
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - historical

  broker:
#    image: znly/druid:0.9.1.1
    build: .
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - broker
    ports:
      - "8082:8082"
